spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://101.235.116.141:3306/eunho
      username: root
      password: 123123


server:
  port: 8080